### ISSUE TITLE
toMomentFormatString function with node v6.7.0

### ISSUE THREAD

**Issue by kol9n93** [MadMG/moment-jdateformatparser#17] opened 2016-10-12 09:58 UTC
Hi. Are there some issues with node 6?
I'm trying to run code 

```
require('moment-jdateformatparser');
(0, _moment2.default)().toMomentFormatString(format);
```

but getting error `TypeError: (0 , _moment2.default)().toMomentFormatString is not a function`

Code `(0 , _moment2.default)()` returns object of type 'Moment'.

**Comment by kol9n93** [comment] 2016-10-12 10:16
I'm sorry. It causes the problem, because npm locates some node-modules of my package in root node_modules catalog in my main application. I don't know why, but my package can't do require('moment-jdateformatparser'). May be you know why?

**Comment by herom** [comment] 2016-10-12 11:15
I'm sorry - currently we're not testing against node.js v6.0.0 and I myself haven't switched to it with my projects either so I'm of no help I'm afraid...

If you'll find the cause/fix it would be awesome if you could share it here 👍

**Comment by kol9n93** [comment] 2016-10-12 11:18
Okay, no problem, thank you for your answer :)

**Comment by kol9n93** [comment] 2016-10-12 12:51
I haven't solve the problem. The following situation causes the problem: I'm trying to require('moment-jdateformatparser), but that script doesn't export anything and my script continue running code after require. It isn't related to node 6. It's be because in this case we have some asynchrony. May you know how to solve the problem?

**Comment by herom** [comment] 2018-06-26 14:51
Closing as there were no updates since more than a year (also our fault...) 🦄

**Closed by herom** 2018-06-26 14:51 UTC
