### ISSUE TITLE
Loading with Require.js doesn't always work as expected

### ISSUE THREAD

**Issue by mflorea** [MadMG/moment-jdateformatparser#20] opened 2017-08-02 11:15 UTC
I'm using the following code to load ``moment-jdateformatparser``:

    require.config({
      paths: {
        'moment': 'path/to/moment',
        'moment-jdateformatparser': 'path/to/moment-jdateformatparser'
      },
      shim: {
        'moment-jdateformatparser': ['moment']
      }
    });

    require(['moment', 'moment-jdateformatparser'], function(moment) {
      moment().toMomentFormatString('yyyy/MM/dd HH:mm');
    });

This fails from time to time complaining that ``toMomentFormatString`` is not available. It happens most often on IE11. The issue is that ``moment-jdateformatparser`` extends ``moment`` using a Require.js callback when require is available (even if moment was previously loaded). Require.js doesn't call the callback immediately but on the next processor cycle (think about setTimeout(0)) even if the required module is already loaded. Thus you have to do this to make it work, which is cumbersome:

    require(['moment-jdateformatparser'], function() {
      // moment-jdateformatparser was loaded but it didn't extend moment yet.
      // We need to put our code in a require callback in order to wait for
      // moment-jdateformatparser to extend moment.
      require(['moment'], function(moment) {
        moment().toMomentFormatString('yyyy/MM/dd HH:mm');
      });
    });

**Comment by herom** [comment] 2017-08-02 11:49
We'll release a new version (`v1.1.0` via npm) today  - could you please check once it's out if you see the same behaviour? This would be awesome 👍

**Comment by mflorea** [comment] 2017-08-04 09:22
I'd love to, if you publish the [WebJar](http://www.webjars.org/) on [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cmoment-jdateformatparser). Thanks.

**Comment by dpeger** [comment] 2018-05-09 10:01
I can confirm that with 1.1.0 `moment-jdateformatparser` this issue is still valid. As already pointed out by @mflorea the problem is the use of the require callback in [lines 184-186](https://github.com/MadMG/moment-jdateformatparser/blob/master/moment-jdateformatparser.js#L184-L186) of `moment-jdateformatparser.js`. By using asynchronous require you get a race condition as `moment` might already be used before `hookMoment` is executed.

**Comment by herom** [comment] 2018-06-26 14:50
Should be fixed by #27, #29 in version `1.2.1`.

**Closed by herom** 2018-06-26 14:50 UTC
